// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://z4leccclhfbsffjka6btmpzpdu.appsync-api.us-west-1.amazonaws.com/graphql',
          region: 'us-west-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-xtndxodvtffcpbg76es7n6cggq'
        }
    }
};

export default config;