// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://l6fwfhm7unar7kviokabq4jwaq.appsync-api.us-west-1.amazonaws.com/graphql',
          region: 'us-west-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-efqhq3bx3be4hdpwoiaahk2ike'
        }
    }
};

export default config;