// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://ztzgax6hgnhhvjq6fqmug6gxqu.appsync-api.us-west-1.amazonaws.com/graphql',
          region: 'us-west-1',
          defaultAuthMode: 'userPool',
        }
    }
};

export default config;